name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }} # Set this in project secrets
  DOCKER_ID:  ${{ secrets.DOCKER_HUB_USERNAME }}  # Set this in project secrets
  RUN_NUMBER: ${{ github.run_number }}  # This is created automatically
  GKE_CLUSTER: your_cluster    # Change to your cluster name .
  GKE_ZONE: your_zome   # Change to your cluster zone here.
  DEPLOYMENT_NAME: your_deployment # Change to your deployment name here.
  CONTAINER_NAME: your_container # Change to your container name (you can find it in the deployment yaml)
  IMAGE: your_image_name # Change to your image name here.

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

   # Test
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install  
    - name: Run tests
      run: npm test
    
    # Login to docker hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:v2.${{ github.run_number }}


    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}


    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$DOCKER_ID/$IMAGE:v2.$RUN_NUMBER


